name: Trigger Jenkins Pipeline

on:
  workflow_dispatch:

jobs:
  trigger:
    name: Build
    runs-on : ubuntu-latest
    steps:
      - name: Trigger Jenkins Pipeline
        uses : appleboy/jenkins-action@master
        with:
          url: ${{secrets.URL}}
          user: ${{secrets.USER}}
          token: ${{secrets.TOKEN}}
          job: ${{secrets.JOBS}}
